### ISSUE TITLE
FOXFIZZ DISPLAY NOT GOOD AT MS EDGE BROWSER

### ISSUE THREAD

**Issue by TranHuuTam** [fongfan999/ff_gear#9]
![image](https://cloud.githubusercontent.com/assets/22553835/21468367/41edc77a-ca40-11e6-930d-3af0cd21296f.png)

See these content at home page when we enter "www.foxfizz.com" into address bar - Microsoft Edge

**Comment by fongfan999** [comment]
Your connection is too weak and cannot load icon successfully, just reload the page to fix the issue.

**Comment by TranHuuTam** [comment]
It's not true. Still you can look at it below:
![image](https://cloud.githubusercontent.com/assets/22553835/21581896/99c7321a-d076-11e6-99d8-29e37d817ee7.png)

Again, I tried to reload it but nothing change.

**Comment by fongfan999** [comment]
I tested the page on my machine and It's working properly.
![image](https://cloud.githubusercontent.com/assets/13912857/21583909/d748b596-d0c6-11e6-94ca-aa057e5909df.png)

**Comment by TranHuuTam** [comment]
![image](https://cloud.githubusercontent.com/assets/22553835/21640065/f310e272-d2a5-11e6-8f64-27525d02cc1c.png)
Oh, now I see it ok.
Greeting for you best seller
